### ISSUE TITLE
Channel does not exist error: also suggest message content intent

### ISSUE THREAD

**Issue by Ricket** [ErdbeerbaerLP/DiscordIntegration-Core#108]
When bot fails to find channel, this is the error in the log: "Channel does not exist, check channel ID and bot permissions on both channel and category"

My issue ended up being that my bot was created several years ago, and Discord since added "intents" and defaulted them off. I had to go enable the message content intent.

Perhaps update this message to _also_ suggest ensuring the bot has the message content intent enabled. It would've saved me some time.

https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/blob/947b6cd85588a6e81d8a2c7cf86a48957d2af1f3/src/main/java/de/erdbeerbaerlp/dcintegration/common/storage/CommandRegistry.java#L37

**Comment by ErdbeerbaerLP** [comment]
Implemented
