### ISSUE TITLE
[Suggestion] Whitelist players only when they have a certain Discord Role

### ISSUE THREAD

**Issue by Razernok** [ErdbeerbaerLP/DiscordIntegration-Core#114]
**Platform**
-
- [x] Forge

**What you want to be added?**
- I would really like the option to whitelist people who have a certain role on discord and deny access if they don't have said role on discord. currently its you just need to role to link minecraft to discord.

**Comment by ErdbeerbaerLP** [comment]
This feature already exists, use the whitelist mode together with the requiredRoles ;)
