### ISSUE TITLE
[BUG] Hang on shutdown

### ISSUE THREAD

**Issue by rathmerdominik** [ErdbeerbaerLP/DiscordIntegration-Core#155]
**What happened?**
- At currently unknown occurrences the bot hangs on shutdown. The reasoning might be because of https://jda.wiki/using-jda/troubleshooting/#shutdown-but-the-process-doesnt-exit

**What should happen?**
- The bot should properly shutdown when asked for it

**Steps to reproduce**
- Start the bot
- Something unknown happens
- Bot does not shut down and hangs

**Version**
- 1.16.5
Minecraft 1.?.?
Mod/plugin:

**Platform**
- [x] Forge
- [ ] Spigot

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-

**Comment by ErdbeerbaerLP** [comment]
This should be fixed, closing.
