### ISSUE TITLE
[BUG] Messages from Discord Webhook are not reaching the in-game interface.

### ISSUE THREAD

**Issue by ray1025** [ErdbeerbaerLP/DiscordIntegration-Core#176]
**What happened?**
-Messages from Discord Webhook are not reaching the in-game interface.

**What should happen?**
-Discord Webhook messages should be transmitted to the in-game interface.

**Steps to reproduce**
-Place the plugin in the folder.
-Complete the setup.
-Run the server.
-Send messages on Discord Webhook.

**Version**
-Minecraft 1.20.4
-plugin: DiscordIntegration-Spigot 3.0.5.1

**Platform**
-Paper

**Config file**
-
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-https://hastebin.com/share/uwewixiyeh.php

**Additional info**
-In Minecraft 1.20.2 with Plugin version 3.0.3, everything was working fine. The issues started after the update.

**Comment by serverwentdown** [comment]
I'm facing the same problem

**Comment by ErdbeerbaerLP** [comment]
There is a config entry to "allowWebhookMessages". Note that this conflicts with the webhook mode of this mod.
